# vim: ts=4 sw=4 et
plugins:
    cloudify_plugin_openstack_neutron_provisioner:
        derived_from: 'cloudify.plugins.manager_plugin'
        properties:
            url: 'https://github.com/Fewbytes/cloudify-plugin-openstack-neutron-provisioner/archive/master.zip'
    cloudify_plugin_openstack_nova_provisioner:
        derived_from: 'cloudify.plugins.manager_plugin'
        properties:
            url: 'https://github.com/ilyash/cloudify-plugin-openstack-nova-provisioner/archive/master.zip'

imports:
    - 'cloudify.types'
    - 'neutron-floatingip-type.yaml'
    - 'neutron-network-type.yaml'
    - 'neutron-port-type.yaml'
    - 'neutron-router-type.yaml'
    - 'neutron-security-group-type.yaml'
    - 'neutron-subnet-type.yaml'
    - 'nova-server-type.yaml'


blueprint:
    name: 'nova-test-timestamp-1392828443'
    nodes:
        -
            name: 'demo_nova_server'
            type: 'nova_server'
            instances:
                deploy: 2
            relationships:
                -
                    # depends_on as temp fix, contained_in does not work with multiple instances
                    type: 'cloudify.relationships.depends_on'
                    target: 'demo_neutron_network_front'
                -
                    type: 'cloudify.relationships.depends_on'
                    target: 'demo_neutron_network_back'
            properties:
                server:
                    # Sugar: resolves name to id (->"image")
                    image_name: 'Ubuntu Precise 12.04 LTS Server 64-bit 20121026 (b)'
                    # Sugar: resolves name to id (->"flavor")
                    flavor_name: 'standard.xsmall'  # 1G RAM, 10G disk (or 30G in old region), 1 CPU
                    key_name: test
                # HP cloud, only for new region, comment out for old region:
                management_network_name: cloudify-admin-network
        -
            name: 'demo_nova_server2'
            type: 'nova_server'
            instances:
                deploy: 2
            relationships:
                -
                    # depends_on as temp fix, contained_in does not work with multiple instances
                    type: 'cloudify.relationships.depends_on'
                    target: 'demo_neutron_network_front'
                -
                    type: 'cloudify.relationships.depends_on'
                    target: 'demo_neutron_network_back'
            properties:
                server:
                    # Sugar: resolves name to id (->"image")
                    image_name: 'Ubuntu Precise 12.04 LTS Server 64-bit 20121026 (b)'
                    # Sugar: resolves name to id (->"flavor")
                    flavor_name: 'standard.small'  # 2G RAM, 2 CPUs
                    key_name: test
                # HP cloud, only for new region, comment out for old region:
                management_network_name: cloudify-admin-network
        -
            name: 'demo_neutron_network_front'
            type: 'neutron_network'
            properties:
                network:
                    name: 'demo_neutron_network_front'
        -
            name: 'demo_neutron_subnet_front'
            type: 'neutron_subnet'
            relationships:
                -
                    type: 'cloudify.relationships.contained_in'
                    target: 'demo_neutron_network_front'
            properties:
                subnet:
                    name: 'neutron_subnet_test'
                    ip_version: 4
                    cidr: '10.10.10.0/24'

        -
            name: 'demo_neutron_network_back'
            type: 'neutron_network'
            properties:
                network:
                    name: 'demo_neutron_network_back'
        -
            name: 'demo_neutron_subnet_back'
            type: 'neutron_subnet'
            relationships:
                -
                    type: 'cloudify.relationships.contained_in'
                    target: 'demo_neutron_network_back'
            properties:
                subnet:
                    name: 'neutron_subnet_test'
                    ip_version: 4
                    cidr: '10.10.20.0/24'

