# vim: ts=4 sw=4 et
plugins:
    cloudify_plugin_openstack_nova_provisioner:
        derived_from: 'cloudify.plugins.manager_plugin'
        properties:
            url: 'https://github.com/ilyash/cloudify-plugin-openstack-nova-provisioner/archive/master.zip'
    # cloudify_plugin_openstack_neutron_provisioner:
    #     derived_from: 'cloudify.plugins.manager_plugin'
    #     properties:
    #         url: 'https://github.com/Fewbytes/cosmo-plugin-openstack-neutron-provisioner/archive/master.zip'

imports:
    - 'cloudify.types'
    # - 'neutron-floatingip-type.yaml'
    # - 'neutron-network-type.yaml'
    # - 'neutron-port-type.yaml'
    # - 'neutron-router-type.yaml'
    # - 'neutron-security-group-type.yaml'
    # - 'neutron-subnet-type.yaml'
    - 'nova-server-type.yaml'


blueprint:
    name: 'nova-test-timestamp-1392824321'
    nodes:
        -
            name: 'demo_nova_server'
            type: 'nova_server'
            instances:
                deploy: 1
            properties:
                server:
                    # Sugar: resolves name to id (->"image")
                    image_name: 'Ubuntu Precise 12.04 LTS Server 64-bit 20121026 (b)'
                    # Sugar: resolves name to id (->"flavor")
                    flavor_name: 'standard.xsmall'  # 1G RAM, 10G disk (or 30G in old region), 1 CPU
                    key_name: test
                # HP cloud, only for new region, comment out for old region:
                management_network_name: cloudify-admin-network
        # -
        #     name: 'neutron_network'
        #     type: 'neutron_network'


