# vim: ts=4 sw=4 et
plugins:
    cloudify_plugin_openstack_neutron_provisioner:
        derived_from: 'cloudify.plugins.remote_plugin'
        properties:
            url: 'https://github.com/Fewbytes/cosmo-plugin-openstack-neutron-provisioner/archive/master.zip'
    cloudify_plugin_openstack_nova_provisioner:
        derived_from: 'cloudify.plugins.remote_plugin'
        properties:
            url: 'NONE_YET'

imports:
    - 'cloudify.types'
    - 'neutron-floatingip-type.yaml'
    - 'neutron-network-type.yaml'
    - 'neutron-port-type.yaml'
    - 'neutron-router-type.yaml'
    - 'neutron-security-group-type.yaml'
    - 'neutron-subnet-type.yaml'
    - 'nova-server-type.yaml'


blueprint:
    name: 'neutron-test-multinic-timestamp-1392711377'
    nodes:
        # -
        #     name: 'nova_server'
        #     type: 'nova_server'
        #     relationships:
        #         -
        #             type: 'cloudify.relationships.connected_to'
        #             target: 'neutron_port'
        #     properties:
        #         server:
        #             name: 'nova_server_test'
        #             flavor: 1
        #             # 'image_name' is a sugar to passing UUID in 'image' parameter
        #             image_name: cirros-0.3.1-x86_64-uec
        #             key_name: test
        #         management_network_name: public
        #         # XXX. More connections and we're screwed. 
        #         # Have search for "connected_to" and target node
        #         # of type "network"
        -
            name: 'neutron_network'
            type: 'neutron_network'
            properties:
                network:
                    name: 'neutron_network_test'
        -
            name: 'neutron_subnet'
            type: 'neutron_subnet'
            relationships:
                -
                    type: 'cloudify.relationships.contained_in'
                    target: 'neutron_network'
            properties:
                subnet:
                    name: 'neutron_subnet_test'
                    ip_version: 4
                    cidr: '10.10.10.0/24'

        -
            name: 'neutron_port'
            type: 'neutron_port'
            properties:
                port:
                    name: 'neutron_test_port'
            relationships:
                -
                    type: 'cloudify.relationships.contained_in'
                    target: 'neutron_network'
                -
                    type: 'cloudify.relationships.connected_to'
                    target: 'security_group_src'
                    source_interfaces:
                        cloudify.interfaces.relationship_lifecycle:
                            - establish: cloudify_plugin_openstack_neutron_provisioner.port.connect_security_group

        -
            name: 'security_group_src'
            type: 'neutron_security_group'
            properties:
                security_group:
                    name: 'neutron_test_security_group_src'
        # -
        #     name: 'security_group_src2'
        #     type: 'neutron_security_group'
        #     properties:
        #         security_group:
        #             name: 'neutron_test_security_group_src2'
